package org.obl.raz

trait EncHPathF[-H <: HPath, -T, +P <: Path] {

  def apply(h:H):T => P
  
}

object EncHPathF {
  
  import  EncHPaths._
  
  private def toBasePath[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect](pth:Path) =
    BasePath[R,A,P](pth.base, pth.path, pth.params, pth.fragment)
  
  def apply[H <: HPath,T,PTH <: Path](f:H => T => PTH) =  new EncHPathF[H, T,PTH] {
    def apply(h:H):T => PTH = f(h)
  }
  
  private def sum[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect](pths:Path*) = {
    toBasePath[R,A,P](PathUtils.mergeAll(pths))
  }
  
  implicit def toHPathF1[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1] =
    apply[EncHPath1[R,A,P,T1], T1,BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.path,  h.value.apply(t1)))  
  

  implicit def toEncHPathF2[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2] = 
    apply[EncHPath2[R,A,P,T1,T2], (T1,T2),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.path,  h.head.value.apply(t1._1), h.value.apply(t1._2)) )  
  

  implicit def toEncHPathF3[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3] =
    apply[EncHPath3[R,A,P,T1,T2,T3], (T1,T2,T3),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.path,  h.head.head.value.apply(t1._1), h.head.value.apply(t1._2), h.value.apply(t1._3)))  
  

  implicit def toEncHPathF4[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4] =
    apply[EncHPath4[R,A,P,T1,T2,T3,T4], (T1,T2,T3,T4),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.path,  h.head.head.head.value.apply(t1._1), h.head.head.value.apply(t1._2), h.head.value.apply(t1._3), h.value.apply(t1._4)))  
  

  implicit def toEncHPathF5[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5] =
    apply[EncHPath5[R,A,P,T1,T2,T3,T4,T5], (T1,T2,T3,T4,T5),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.path,  h.head.head.head.head.value.apply(t1._1), h.head.head.head.value.apply(t1._2), h.head.head.value.apply(t1._3), h.head.value.apply(t1._4), h.value.apply(t1._5)))  
  

  implicit def toEncHPathF6[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6] =
    apply[EncHPath6[R,A,P,T1,T2,T3,T4,T5,T6], (T1,T2,T3,T4,T5,T6),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.path,  h.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.value.apply(t1._2), h.head.head.head.value.apply(t1._3), h.head.head.value.apply(t1._4), h.head.value.apply(t1._5), h.value.apply(t1._6)))  
  

  implicit def toEncHPathF7[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7] =
    apply[EncHPath7[R,A,P,T1,T2,T3,T4,T5,T6,T7], (T1,T2,T3,T4,T5,T6,T7),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.value.apply(t1._3), h.head.head.head.value.apply(t1._4), h.head.head.value.apply(t1._5), h.head.value.apply(t1._6), h.value.apply(t1._7)))  
  

  implicit def toEncHPathF8[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8] =
    apply[EncHPath8[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8], (T1,T2,T3,T4,T5,T6,T7,T8),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.value.apply(t1._4), h.head.head.head.value.apply(t1._5), h.head.head.value.apply(t1._6), h.head.value.apply(t1._7), h.value.apply(t1._8)))  
  

  implicit def toEncHPathF9[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9] =
    apply[EncHPath9[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9], (T1,T2,T3,T4,T5,T6,T7,T8,T9),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.value.apply(t1._5), h.head.head.head.value.apply(t1._6), h.head.head.value.apply(t1._7), h.head.value.apply(t1._8), h.value.apply(t1._9)))  
  

  implicit def toEncHPathF10[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10] =
    apply[EncHPath10[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.value.apply(t1._6), h.head.head.head.value.apply(t1._7), h.head.head.value.apply(t1._8), h.head.value.apply(t1._9), h.value.apply(t1._10)))  
  

  implicit def toEncHPathF11[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11] =
    apply[EncHPath11[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.value.apply(t1._7), h.head.head.head.value.apply(t1._8), h.head.head.value.apply(t1._9), h.head.value.apply(t1._10), h.value.apply(t1._11)))  
  

  implicit def toEncHPathF12[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12] =
    apply[EncHPath12[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.value.apply(t1._8), h.head.head.head.value.apply(t1._9), h.head.head.value.apply(t1._10), h.head.value.apply(t1._11), h.value.apply(t1._12)))  
  

  implicit def toEncHPathF13[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13] =
    apply[EncHPath13[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.head.value.apply(t1._8), h.head.head.head.head.value.apply(t1._9), h.head.head.head.value.apply(t1._10), h.head.head.value.apply(t1._11), h.head.value.apply(t1._12), h.value.apply(t1._13)))  
  

  implicit def toEncHPathF14[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14] =
    apply[EncHPath14[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.head.head.value.apply(t1._8), h.head.head.head.head.head.value.apply(t1._9), h.head.head.head.head.value.apply(t1._10), h.head.head.head.value.apply(t1._11), h.head.head.value.apply(t1._12), h.head.value.apply(t1._13), h.value.apply(t1._14)))  
  

  implicit def toEncHPathF15[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15] =
    apply[EncHPath15[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.head.head.head.value.apply(t1._8), h.head.head.head.head.head.head.value.apply(t1._9), h.head.head.head.head.head.value.apply(t1._10), h.head.head.head.head.value.apply(t1._11), h.head.head.head.value.apply(t1._12), h.head.head.value.apply(t1._13), h.head.value.apply(t1._14), h.value.apply(t1._15)))  
  

  implicit def toEncHPathF16[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16] =
    apply[EncHPath16[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.head.head.head.head.value.apply(t1._8), h.head.head.head.head.head.head.head.value.apply(t1._9), h.head.head.head.head.head.head.value.apply(t1._10), h.head.head.head.head.head.value.apply(t1._11), h.head.head.head.head.value.apply(t1._12), h.head.head.head.value.apply(t1._13), h.head.head.value.apply(t1._14), h.head.value.apply(t1._15), h.value.apply(t1._16)))  
  

  implicit def toEncHPathF17[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17] =
    apply[EncHPath17[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.head.head.head.head.head.value.apply(t1._8), h.head.head.head.head.head.head.head.head.value.apply(t1._9), h.head.head.head.head.head.head.head.value.apply(t1._10), h.head.head.head.head.head.head.value.apply(t1._11), h.head.head.head.head.head.value.apply(t1._12), h.head.head.head.head.value.apply(t1._13), h.head.head.head.value.apply(t1._14), h.head.head.value.apply(t1._15), h.head.value.apply(t1._16), h.value.apply(t1._17)))  
  

  implicit def toEncHPathF18[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18] =
    apply[EncHPath18[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._8), h.head.head.head.head.head.head.head.head.head.value.apply(t1._9), h.head.head.head.head.head.head.head.head.value.apply(t1._10), h.head.head.head.head.head.head.head.value.apply(t1._11), h.head.head.head.head.head.head.value.apply(t1._12), h.head.head.head.head.head.value.apply(t1._13), h.head.head.head.head.value.apply(t1._14), h.head.head.head.value.apply(t1._15), h.head.head.value.apply(t1._16), h.head.value.apply(t1._17), h.value.apply(t1._18)))  
  

  implicit def toEncHPathF19[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19] =
    apply[EncHPath19[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._8), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._9), h.head.head.head.head.head.head.head.head.head.value.apply(t1._10), h.head.head.head.head.head.head.head.head.value.apply(t1._11), h.head.head.head.head.head.head.head.value.apply(t1._12), h.head.head.head.head.head.head.value.apply(t1._13), h.head.head.head.head.head.value.apply(t1._14), h.head.head.head.head.value.apply(t1._15), h.head.head.head.value.apply(t1._16), h.head.head.value.apply(t1._17), h.head.value.apply(t1._18), h.value.apply(t1._19)))  
  

  implicit def toEncHPathF20[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20] =
    apply[EncHPath20[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._8), h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._9), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._10), h.head.head.head.head.head.head.head.head.head.value.apply(t1._11), h.head.head.head.head.head.head.head.head.value.apply(t1._12), h.head.head.head.head.head.head.head.value.apply(t1._13), h.head.head.head.head.head.head.value.apply(t1._14), h.head.head.head.head.head.value.apply(t1._15), h.head.head.head.head.value.apply(t1._16), h.head.head.head.value.apply(t1._17), h.head.head.value.apply(t1._18), h.head.value.apply(t1._19), h.value.apply(t1._20)))  
  

  implicit def toEncHPathF21[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21] =
    apply[EncHPath21[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._8), h.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._9), h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._10), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._11), h.head.head.head.head.head.head.head.head.head.value.apply(t1._12), h.head.head.head.head.head.head.head.head.value.apply(t1._13), h.head.head.head.head.head.head.head.value.apply(t1._14), h.head.head.head.head.head.head.value.apply(t1._15), h.head.head.head.head.head.value.apply(t1._16), h.head.head.head.head.value.apply(t1._17), h.head.head.head.value.apply(t1._18), h.head.head.value.apply(t1._19), h.head.value.apply(t1._20), h.value.apply(t1._21)))  
  

  implicit def toEncHPathF22[R <: RelativePathAspect,A <: CanAddAspect,P <: CanHavePrefixAspect,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22] =
    apply[EncHPath22[R,A,P,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22], (T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22),BasePath[R,A,P]](h => t1 => sum[R,A,P](h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.path,  h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._1), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._2), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._3), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._4), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._5), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._6), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._7), h.head.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._8), h.head.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._9), h.head.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._10), h.head.head.head.head.head.head.head.head.head.head.head.value.apply(t1._11), h.head.head.head.head.head.head.head.head.head.head.value.apply(t1._12), h.head.head.head.head.head.head.head.head.head.value.apply(t1._13), h.head.head.head.head.head.head.head.head.value.apply(t1._14), h.head.head.head.head.head.head.head.value.apply(t1._15), h.head.head.head.head.head.head.value.apply(t1._16), h.head.head.head.head.head.value.apply(t1._17), h.head.head.head.head.value.apply(t1._18), h.head.head.head.value.apply(t1._19), h.head.head.value.apply(t1._20), h.head.value.apply(t1._21), h.value.apply(t1._22)))  

}